# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    url: '#research'
    weight: 20
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Conferences
    url: '#conferences'
    weight: 40
  - name: Resources
    url: '#resources'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60

# Sub-home menu
  - name: About
    weight: 15
    url: '#about'
  - name: Education
    url: '#education'
    parent: "About"
    weight: 20
  # - name: Technical Skills
  #   url: '#skills'
  #   parent: "About"
  #   weight: 30
  - name: CV
    url: uploads/ywang_cv.pdf
    parent: "About"
    weight: 40
  - name: About Me
    url: '/aboutme/'
    parent: "About"
    weight: 50
  # - name: Pictures of my dog
  #   url: '/spamwise/'
  #   parent: "About"
  #   weight: 50
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70

# Sub-home menu
  #- name: ROMS for Ultra Beginners
    #url: '/roms/'
    #parent: "Resources"
    #weight: 20
  - name: Interested in applying to the MIT-WHOI Joint Program?
    #url: '/roms/'
    url: 'https://mit.whoi.edu/admissions/apply/jp-applicant-support-knowledgebase-jp-ask/'
    parent: "Resources"
    weight: 30